services:
  gui:
    build:
      context: .
      dockerfile: ./gui/Dockerfile
    image: scratch-gui
    container_name: scratch-gui
    restart: always
    ports:
      - "8601:8601" # Node.js chạy trên cổng 3000
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
    - "8100:80" 
    volumes:
    - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
    - gui
    networks:
    - webnet
networks:
  webnet:
    driver: bridge
